# IMPORTANT: please replace all placeholders 
# in this file that start with "YOUR_", such as "YOUR_URL.TLD", 
# "YOUR_USERNAME", "YOUR_SITE_TITLE", etc., with your actual data.

# The base URL of the site; the only required configuration variable.
base_url = "https://zmizuky.github.io/IanMatrix/"

# The site theme to use.
theme = "linkita"

# For overriding the default output directory `public`, set it to another value (e.g.: "docs")
# output_dir = "public"

# Whether dotfiles at the root level of the output directory are preserved when (re)building the site.
# Enabling this also prevents the deletion of the output folder itself on rebuilds.
# preserve_dotfiles_in_output = false

# When set to "true", the Sass files in the `sass` directory in the site root are compiled.
# Sass files in theme directories are always compiled.
compile_sass = false

# When set to "true", the generated HTML files are minified.
minify_html = false

# A list of glob patterns specifying asset files to ignore when the content
# directory is processed. Defaults to none, which means that all asset files are
# copied over to the `public` directory.
# Example:
#     ignored_content = ["*.{graphml,xlsx}", "temp.*", "**/build_folder"]
# ignored_content = []

# Similar to ignored_content, a list of glob patterns specifying asset files to
# ignore when the static directory is processed. Defaults to none, which means
# that all asset files are copied over to the `public` directory
# ignored_static = []

# When set to "all", paginated pages are not a part of the sitemap, default is "none"
exclude_paginated_pages_in_sitemap = "all"

# The number of articles to include in the feed. All items are included if
# this limit is not set (the default).
# feed_limit = 20

# When set to "true", files in the `static` directory are hard-linked. Useful for large
# static files. Note that for this to work, both `static` and the
# output directory need to be on the same filesystem. Note that the theme's `static`
# files are always copied, regardless of this setting.
# hard_link_static = false

# When set to "false", Sitemap.xml is not generated
generate_sitemap = true

# When set to "false", robots.txt is not generated
generate_robots_txt = true

# The default author for pages
author = "Ian Guizeline"

# The default language; used in feeds.
default_language = "pt"

# Default language is English

# The site title and description; used in feeds by default.
title = "IanMatrix"
description = "Novo post do IanMatrix"

# When set to "true", a search index is built from the pages and section
# content for `default_language`.
build_search_index = true

# When set to "true", a feed is automatically generated.
generate_feeds = true

# The filenames to use for the feeds. Used as the template filenames, too.
# Defaults to ["atom.xml"], which has a built-in template that renders an Atom 1.0 feed.
# There is also a built-in template "rss.xml" that renders an RSS 2.0 feed.
feed_filenames = ["atom.xml"]

# The taxonomies to be rendered for the site and their configuration of the default languages
# Example:
#     taxonomies = [
#       {name = "tags", feed = true}, # each tag will have its own feed
#       {name = "tags"}, # you can have taxonomies with the same name in multiple languages
#       {name = "categories", paginate_by = 5},  # 5 items per page for a term
#       {name = "authors"}, # Basic definition: no feed or pagination
#     ]
#
taxonomies = [
	{ name = "tags", feed = true }
]

# Additional languages definition
# You can define language specific config values and translations:
# title, description, generate_feeds, feed_filenames, taxonomies, build_search_index
# as well as its own search configuration and translations (see above for details on those)
#
# For example
# [languages.fr]
# title = "Mon blog"
# generate_feeds = true
# taxonomies = [
#    {name = "auteurs"},
#    {name = "tags"},
# ]
# build_search_index = false

# Configuration of the Markdown rendering
[markdown]
# When set to "true", emoji aliases translated to their corresponding
# Unicode emoji equivalent in the rendered Markdown files. (e.g.: :smile: => ðŸ˜„)
render_emoji = false

# CSS class to add to external links (e.g. "external-link")
# external_links_class =

# Whether external links are to be opened in a new tab
# If this is true, a `rel="noopener"` will always automatically be added for security reasons
# external_links_target_blank = false

# Whether to set rel="nofollow" for all external links
# external_links_no_follow = false

# Whether to set rel="noreferrer" for all external links
# external_links_no_referrer = false

# Whether smart punctuation is enabled (changing quotes, dashes, dots in their typographic form)
# For example, `...` into `â€¦`, `"quote"` into `â€œcurlyâ€` etc
smart_punctuation = true

# Whether parsing of definition lists is enabled
# definition_list = false

# Whether to set decoding="async" and loading="lazy" for all images
# When turned on, the alt text must be plain text.
# For example, `![xx](...)` is ok but `![*x*x](...)` isnâ€™t ok
# lazy_async_image = false

# Whether footnotes are rendered in the GitHub-style (at the bottom, with back references) or plain (in the place, where they are defined)
# bottom_footnotes = false

# When set to "true", support for GitHub-style alerts, a.k.a. callouts or admonitions, is enabled in the Markdown parser.
# For example, this Markdown syntax:
#
#     > [!NOTE]
#     > alert note
#
# will result in the following generated HTML:
#
#     <blockquote class="markdown-alert-note">
#     <p>alert note</p>
#     </blockquote>
#
# where the CSS class name suffix may be `note`, `tip`, `important`, `warning`, or `caution`, depending on the alert type.
# Visual appearance depends on theme-level support; refer to your theme's documentation for more information.
# github_alerts = false

# This determines whether to insert a link for each header like the ones you can see on this site if you hover over
# a header.
# The default template can be overridden by creating an `anchor-link.html` file in the `templates` directory.
# This value can be "left", "right", "heading" or "none".
# "heading" means the full heading becomes the text of the anchor.
# See "Internal links & deep linking" in the documentation for more information.
# insert_anchor_links = "none"

# Syntax highlighting configuration (optional)
[markdown.highlighting]
# When set to "true", missing highlight languages are treated as errors. Defaults to false but recommended to set to true.
error_on_missing_language = false

# Whether to use inline hex colours (`inline`) or CSS classes (`class`) 
style = "inline"

# If you use a single theme, put its name here. See the syntax highlighting  page for the possible choices.
theme = "catppuccin-mocha"

# If you want light/dark themes, use the 2 fields below instead. See the syntax highlighting  page for the possible choices.
light_theme = ""
dark_theme = ""

# A list of files for additional JSON TextMate grammars
extra_grammars = []

# A list of files for additional JSON TextMate themes
extra_themes = []

# Configuration of the link checker.
# [link_checker]
# Skip link checking for external URLs that start with these prefixes
# skip_prefixes = [
#     "http://[2001:db8::]/",
# ]

# Skip anchor checking for external URLs that start with these prefixes
# skip_anchor_prefixes = [
#     "https://caniuse.com/",
# ]

# Treat internal link problems as either "error" or "warn", default is "error"
# internal_level = "error"

# Treat external link problems as either "error" or "warn", default is "error"
# external_level = "error"

# Various slugification strategies, see below for details
# Defaults to everything being a slug
# [slugify]
# paths = "on"
# taxonomies = "on"
# anchors = "on"
# Whether to remove date prefixes for page path slugs.
# For example, content/posts/2016-10-08_a-post-with-dates.md => posts/a-post-with-dates
# When true, content/posts/2016-10-08_a-post-with-dates.md => posts/2016-10-08-a-post-with-dates
# paths_keep_dates = false

# [search]
# Whether to include the title of the page/section in the index
# include_title = true
# Whether to include the description of the page/section in the index
# include_description = false
# Whether to include the RFC3339 datetime of the page in the search index
# include_date = false
# Whether to include the path of the page/section in the index (the permalink is always included)
# include_path = false
# Whether to include the rendered content of the page/section in the index
# include_content = true
# At which code point to truncate the content to. Useful if you have a lot of pages and the index would
# become too big to load on the site. Defaults to not being set.
# truncate_content_length = 100

# Whether to produce the search index as a javascript file or as a JSON file
# Accepted values:
# - "elasticlunr_javascript", "elasticlunr_json"
# - "fuse_javascript", "fuse_json"
# index_format = "elasticlunr_javascript"

# You can put any kind of data here. The data
# will be accessible in all templates
# Example:
#     [extra]
#     your_key = "your_value"
#
# key value will be available using {{ config.extra.your_key }} in templates
#
[extra]
# Enable KaTeX math formula support globally.
# Default value: false
math = true

# Enable Mermaid support globally.
# Default value: false
mermaid = false

# Enable comments globally.
# Default value: false
comment = true

# Title separator.
title_separator = " | "

# The top menu.
# See "extra.menus".
header_menu_name = "header_links"

# See "extra.menus".
# menu_i18n = true

# If you disable default favicons, you can use
# the inject support to set your own favicons.
# Default value: false
disable_default_favicon = false

# If you want to implement the JS code
# yourself, set to true and use the inject support.
# Default value: false
disable_javascript = false

# Use a CDN for libraries like KaTeX.
# Default value: false
use_cdn = false

# Use relative urls.
# It doesn't apply for content yet.
# Default value: false
relative_urls = false

# If you want to view the site without a webserver
# set this and "relative_urls" to true.
# Default value: false
ugly_urls = false

# Prioritize summary over description.
# Default value: false
page_summary_on_paginator = true

# Reverse the order of prev and next post links.
# Default value: false
invert_page_navigation = false

# Header buttons.
# Valid values:
#  "site_title", "home_button", "theme_select", "theme_button",
#  "search_button", "translations_select", "translations_button".
# Can be set to an empty array.
# header_buttons = ["site_title", "theme_select", "search_button", "translations_select"]

# What info is shown on post pages.
# Valid "when" values:
#  "date", "date_updated", "reading_time", "word_count", "authors", "tags", "".
# The "prepend" and "append" are used when the value of "when" is defined for the page.
# e.g. [{when="", prepend="Page Info: "},{when="date",prepend="Published on "},{when="authors",prepend="By "}]
# page_info = [{ when="date" }, { when="date_updated", prepend="(", append=")" }, { when="reading_time" }]

# What info is shown for posts on paginators.
# page_info_on_paginator = [{ when="date" }, { when="reading_time" }]

# Enable table of contents on all pages.
# If not set, toc is enabled only on posts.
# If set to false, toc is disabled on all pages.
# Type: boolean or object
# toc = true

# Style config
[extra.style]
# The custom background color.
bg_color = "#f4f4f5"
# The custom background color in dark mode.
bg_dark_color = "#121212"

# Enable header blur.
header_blur = false

# The custom header color, only available
# when "header_blur" is false.
header_color = "#e4e4e7"
# The custom header color in dark mode, only available
# when "header_blur" is false.
header_dark_color = "#282828"

# Menus
[extra.menus]
header_links = [
  { url = "", name = "Blog"},
  { url = "@/pages/archive.md", name = "Arquivos" },
  { url = "$BASE_URL/tags/", name = "Tags" },
  { url = "@/pages/projects/_index.md", name = "Projetos" }
  
]

# Profiles
[extra.profiles.YOUR_USERNAME]

# The path to your profile photo.
# e.g. "icons/github.svg"
avatar_url = "profile.png"

# A description of what is in the avatar.
avatar_alt = ""

# Invert avatar color in dark mode.
# Default value: false
avatar_invert = false

# Profile name.
# Default value: the username
name = "Ian Guizeline"

# Profile bio.
# Supports Markdown.
bio = "Welcome to my personal site!"

# Social icons.
# "name" should be the file name of "static/icons/*.svg" or
# the icon name of https://simpleicons.org/
# "url" supports "$BASE_URL".
# Other variables: "urls", "title", "titles".
social = [
    { name = "bluesky", url = "https://bsky.app/profile/username" },
    { name = "github", url = "https://github.com/username" },
    { name = "email", url = "mailto:example@example.com" },
    { name = "rss", url = "$BASE_URL/atom.xml" },
]

[extra.profiles.YOUR_USERNAME.open_graph]

# Set if you have a Fediverse account.
#  handle â€“ Your Fediverse handle.
#  domain â€“ Your Fediverse instance.
#  url â€“ Your Fediverse account URL. Optional.
# Example for @me@mastodon.social:
# { handle = "me", domain = "mastodon.social" }
# fediverse_creator = { handle = "", domain = "" }

# The page footer
[extra.footer]
# Replace with the correct year.
# Default value: the current year
since = 2026

# Replace with the URL of the license you want.
# No default value. Supports "$BASE_URL".
license_url = "https://creativecommons.org/licenses/by-sa/4.0/deed"

# Replace "YOUR_NAME" with your name and "CC BY-SA 4.0" with the name of the license you want.
copyright = "&copy; $YEAR Ian Guizeline &vert; [CC BY-SA 4.0]($LICENSE_URL)"

# Language specific options
# For English
[extra.languages.pt]

# No default value.
locale = "pt_BR"

# See chrono docs:
#  https://docs.rs/chrono/0.4.42/chrono/format/strftime/
# Default value: "%F"
date_format = "%-d %b %Y"

# Default value: extra.page_info
# page_info = []

# Default value: extra.page_info_on_paginator
# page_info_on_paginator = []

# Default value: extra.header_menu_name
# header_menu_name = "menu_name"

# Default value: extra.header_buttons
# header_buttons = []

# To set a different lang attribute of the document.
# Also changes the interface language. e.g. "en-GB".
# hreflang = ""

# To format numbers for a different locale. e.g. "en-GB".
# Useful if lang is not a valid locale.
# num_format = ""

# Set a description for taxonomy pages.
[extra.languages.en.taxonomy_descriptions]
tags = "A map of all tags on this site. Start exploring!"

# Set a description for term pages.
# "$NAME" will be automatically replaced.
[extra.languages.en.term_descriptions]
tags = "Browse articles related to $NAME. Start exploring!"
