[[project]]
name = "iMatrix"
desc = "Uma engine simples feita com SDL3 e documentada no blog"
tags = ["engine"]
links = [
    { name = "homepage", url = "$BASE_URL/pages/projects/iMatrix/", newtab = false },
    { name = "github", url = "https://github.com/zMizuky/iMatrix", newtab = false }
]
